uci:
  to-services:
    dhcp:
      - odhcpd
      - dnsmasq
  dependencies:
    network:
      - device-names
    firewall:
      - network
    dhcp:
      - network

default-host: router

hosts:
  router:
    source: ./router/
    server:
      addr: 111.111.111.111
      user: root
    params:
      pppoe:
        username: john@doe.com
        password: 1111111
      hardware:
        nic1:
          macaddr: 00:00:00:00:00:00
        nic2:
          macaddr: 00:00:00:00:00:00
      wireguard:
        client:
          private_key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
          public_key: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=
          addr: 111.111.111.111/32
        server:
          public_key: CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC=
          addr: my.wireguard.server.com
          port: 56789
