#!/usr/bin/env bash
set -euo pipefail
BASEDIR="$(realpath "$(dirname "$0")")"
VMDIR="$(dirname "${BASEDIR}")/.vms"
mkdir -p "$VMDIR"

HOST="$1"

play() {
	"$(dirname "${BASEDIR}")/play" "$@"
}

BASE_IMAGE="${VMDIR}/${HOST}.img"

if ! [ -f "$BASE_IMAGE" ]; then
	play build-image "$HOST" "${VMDIR}"
fi

vboxmanage createvm \
	--name "$HOST" --ostype Linux_x64 --basefolder "${VMDIR}" --register

vboxmanage modifyvm "$HOST" \
	--cpus 1 --memory 128 --vram 4 --boot1 disk --audio-driver none

vboxmanage convertfromraw \
	--format VDI "$BASE_IMAGE" "${VMDIR}/${HOST}/${HOST}.vdi"

vboxmanage storagectl "$HOST" \
	--name 'IDE' --add ide

vboxmanage storageattach "$HOST" \
	--storagectl 'IDE' --port 0 --device 0 --type hdd --medium "${VMDIR}/${HOST}/${HOST}.vdi"

index=1
while [ -n "$(play vaal --host="${HOST}" get ".params.vm.nic${index}")" ]; do
	net_type=$(play vaal --host="${HOST}" get ".params.vm.nic${index}.type")

	if [[ "$net_type" == "intnet" ]]; then
		network="--intnet${index} $(play vaal --host="${HOST}" get ".params.vm.nic${index}.network")"
	elif [[ "$net_type" == "hostonly" ]]; then
		network="--hostonlyadapter${index} $(play vaal --host="${HOST}" get ".params.vm.nic${index}.network")"
	fi

	nic="--nic${index} ${net_type}"
	mac=$(play vaal --host="${HOST}" get ".params.vm.nic${index}.macaddr")
	if [ -n "$mac" ]; then
		mac="--macaddress${index} ${mac//:/}"
	fi

	vboxmanage modifyvm "${HOST}" $nic $network $mac

	((index = index + 1))
done
