#!/usr/bin/env bash

set -euo pipefail

TEMPDIR="$(mktemp --directory)"
trap 'rm -rf $TEMPDIR' EXIT

mkdir "${TEMPDIR}/bin"
mkdir "${TEMPDIR}/custom-files"

HOST="$1"

./playvaal --host="$HOST" sync --to-directory="${TEMPDIR}/custom-files"

PACKAGES="wireguard-tools kmod-wireguard ip-full rp-pppoe-server"

docker run \
	--rm \
	--volume "${TEMPDIR}/bin:/builder/bin" \
	--volume "${TEMPDIR}/custom-files:/builder/custom-files" \
	--interactive \
	--tty \
	openwrt/imagebuilder \
	make image PROFILE=generic PACKAGES="$PACKAGES" FILES=custom-files

mkdir -p "./.vm"
gzip -dk "${TEMPDIR}/bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img.gz" || true
cp "${TEMPDIR}/bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img" ".vm/${HOST}.img"
