#!/usr/bin/env bash

set -euo pipefail

VMDIR="$(realpath ./.vm)"
mkdir -p "$VMDIR"

HOST="$1"

BASE_IMAGE="${VMDIR}/${HOST}.img"

if ! [ -f "$BASE_IMAGE" ]; then
	./image "$HOST"
fi

vboxmanage createvm \
	--name "$HOST" --ostype Linux_x64 --basefolder "${VMDIR}" --register

vboxmanage modifyvm "$HOST" \
	--cpus 1 --memory 128 --vram 4 --boot1 disk --audio-driver none

vboxmanage convertfromraw \
	--format VDI "$BASE_IMAGE" "${VMDIR}/${HOST}/${HOST}.vdi"

vboxmanage storagectl "$HOST" \
	--name 'IDE' --add ide

vboxmanage storageattach "$HOST" \
	--storagectl 'IDE' --port 0 --device 0 --type hdd --medium "${VMDIR}/${HOST}/${HOST}.vdi"

index=1
while [ -n "$(./playvaal --host="${HOST}" get ".params.vm.nic${index}")" ]; do
	net_type=$(./playvaal --host="${HOST}" get ".params.vm.nic${index}.type")

	if [[ "$net_type" == "intnet" ]]; then
		network="--intnet${index} $(./playvaal --host="${HOST}" get ".params.vm.nic${index}.network")"
	elif [[ "$net_type" == "hostonly" ]]; then
		network="--hostonlyadapter${index} $(./playvaal --host="${HOST}" get ".params.vm.nic${index}.network")"
	fi

	nic="--nic${index} ${net_type}"
	mac=$(./playvaal --host="${HOST}" get ".params.vm.nic${index}.macaddr")
	if [ -n "$mac" ]; then
		mac="--macaddress${index} ${mac//:/}"
	fi

	vboxmanage modifyvm "${HOST}" $nic $network $mac

	((index = index + 1))
done
